### ISSUE TITLE
L15 Compilation error in v0.9.59

### ISSUE THREAD

**Issue by msfujino** [lolren/nrf54-arduino-core#87]
When I tried to build an nRF54L15 sketch that worked in v0.3.6 using v0.9.59, I got the following compilation error:
What information do you need?

```
Invalid FQBN: getting build properties for board nrf54l15clean:nrf54l15clean:xiao_nrf54l15: invalid option 'clean_power'

Compilation error: Invalid FQBN: getting build properties for board nrf54l15clean:nrf54l15clean:xiao_nrf54l15: invalid option 'clean_power'
```

Even with the LM20A sketch, it doesn't work properly when trying to use the SD card (SPI) and SSD1306 (I2C) simultaneously. There might be a connection.

**Comment by lolren** [comment]
> When I tried to build an nRF54L15 sketch that worked in v0.3.6 using v0.9.59, I got the following compilation error: What information do you need?
> 
> ```
> Invalid FQBN: getting build properties for board nrf54l15clean:nrf54l15clean:xiao_nrf54l15: invalid option 'clean_power'
> 
> Compilation error: Invalid FQBN: getting build properties for board nrf54l15clean:nrf54l15clean:xiao_nrf54l15: invalid option 'clean_power'
> ```
> 
> Even with the LM20A sketch, it doesn't work properly when trying to use the SD card (SPI) and SSD1306 (I2C) simultaneously. There might be a connection.

Can i have the sketch or snippet that causes this? is this still an issue?

**Comment by msfujino** [comment]
I verified this in v0.9.124. The compilation error no longer occurs.

**Comment by lolren** [comment]
Will close this. Thank you for testing.
