### ISSUE TITLE
Cannot get SD Card to initialize after v0.9.133

### ISSUE THREAD

**Issue by TMRh20** [lolren/nrf54-arduino-core#91]
Hi, me again!

I am using `D8=SCK, D9=MISO, D10=MOSI, D2=SS` on a XIAO nRF54L15 board and cannot seem to get an SD card working in any versions after 0.9.133 using the stock SD library.

I've tried everything I think is obvious and it just refuses to work. I know the wiring etc is correct because it does work with previous versions.

Using Arduino IDE v2.3.10 in Windows 11 and cannot figure out if this is a me issue or a core issue.

**Comment by lolren** [comment]
Thank you for reporting. The SPI went trough a lot of changes lately. is 0.9.133 working from what I understand?

**Comment by TMRh20** [comment]
Yes 0.9.133 is working. After that I'm getting installation and/or uploading/compilation errors up to v0.9.155 and higher which then won't work with SD

**Comment by lolren** [comment]
A fix will come in the next version later. Working on it :D

**Comment by lolren** [comment]
Should work in the newest version. 
For some reason, SPI is limited to 4Mhz, so I will have to investigate this in the near future.

**Comment by TMRh20** [comment]
Thanks! SD is working but to compile v0.9.196 I had to add `int32_t` to line 469 of npm1300.cpp:
```
AppData\Local\Arduino15\packages\nrf54l15clean\hardware\nrf54l15clean\0.9.196\libraries\Nrf54L15-Clean-Implementation\src\npm1300.cpp:469:5: error: 'g_dischargeLimitUa' was not declared in this scope
     g_dischargeLimitUa = (int32_t)ma * 1000;
```

```cpp
    int32_t g_dischargeLimitUa = (int32_t)ma * 1000;
```

**Comment by TMRh20** [comment]
All working in v0.9.197

**Comment by lolren** [comment]
Properly implemented SPI in latest core.
